clean up
dopex-io/0dte pull request #2
Opened 2023-03-21 22:37 UTC by garyunwin42

2023-04-01 21:08 UTC, 0xYYC commented on contracts/Zdte.sol
> +                : ((shortStrike - longStrike) / shortStrike) * 1 ether / STRIKE_DECIMALS - longPremium + shortPremium
The correct one is formulae for call is : ( shortStrike - longStrike ) * 1e18 / shortStrike

2023-04-09 18:25 UTC, witherblock requested changes

2023-04-09 18:25 UTC, witherblock commented on contracts/Zdte.sol
> +    }
lets pass both strike and expiry to this public view for a better interface

2023-04-10 13:06 UTC, witherblock commented on contracts/Zdte.sol
> +    }
Also how would u differentiate call and puts

2023-04-10 13:20 UTC, garyunwin42 commented on contracts/Zdte.sol
> +    }
im not sure. i thought vol is gonna be independent of call / put, only a function of strike

2023-04-11 01:05 UTC, witherblock commented on contracts/Zdte.sol
> +    }
Ofc not, volatility is always different for calls and puts, only in ideal scenarios they remain same

2023-04-17 03:38 UTC, closed without merging